image:
#  repository: registry.gitlab.com/samsonnik1997/k8s/front
#  tag: "main"
  pullPolicy: Always

#imagePullSecrets:
#  - name: docker-registry

service:
  port: 443

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  path: "/second"
  pathType: Prefix
