apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
 name: k8s-action-runner
 namespace: github-runner
spec:
 replicas: 1
 template:
   spec:
     repository: Samsonnik/k8s-gitHub
