apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  nginx.conf: |-
{{ .Files.Get "files/nginx.conf" | indent 4 }}
