apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-front
  labels:
    app: {{ .Release.Name }}-front
spec:
  containers:
  - name: front
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: nginx.conf
  imagePullSecrets:
      - name: gitlab-registry-secret
  volumes:
  - name: config-volume
    configMap:
      name: {{ .Release.Name }}-nginx-config
