name: Run Self-Hosted Runner with Kaniko

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-job:

    runs-on: self-hosted
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug

    steps:

      - name: Create Docker config.json
        run: |
          cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "docker-registry.docker-registry.svc.cluster.local:5000": {
                "auth":  "$(echo -n "evgen:evgen" | base64 -w0)"
              }
            }
          }
          EOF

      - name: Log files in 1.images
        run: |
          echo "Files in /github/workspace/1.images:"
          ls -la /1.images

      - name: Build and Push
        run: |
          /kaniko/executor \
            --context "1.images" \
            --dockerfile "dockerfile" \
            --destination "docker-registry.docker-registry.svc.cluster.local:5000/github-front:latest" \
            --ignore-path=/product_uuid \
            --ignore-path=/sys \
            --ignore-path=/proc \
            --insecure
