name: Run Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version || echo "Docker not found"
