name: Run Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker build with Kaniko
        uses: docker/setup-buildx-action@v2
        with:
          driver: kaniko
          context: ./1.images/
          file: ./1.images/dockerfile
          tags: docker-registry.docker-registry.svc.cluster.local:5000/github-front:latest
          push: true
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
