name: Run Self-Hosted Runner with Kaniko

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-job:

    runs-on: self-hosted

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Логирование информации о среде выполнения
      - name: Log environment details
        run: |
          echo "Running on host: $(hostname)"
          echo "Current directory: $(pwd)"
          echo "Environment variables:"
          printenv | grep -E 'RUNNER_|GITHUB_'

      # Шаг 3: Сборка и отправка Docker-образа с помощью Kaniko
      - name: Build and push with Kaniko
        uses: gcr.io/kaniko-project/executor@latest
        with:
          context: ./1.images/
          dockerfile: ./1.images/Dockerfile
          destination: docker-registry.docker-registry.svc.cluster.local:5000/github-front:latest
          username: evgen
          password: evgen
          insecure: true
          skip-tls-verify: true
