name: Run Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-job:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          cd 1.images/
          docker build -t github-front:latest .
